name: hn_app
description: A new Flutter application.

dependencies:
  url_launcher: any

  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.1

  http: ^0.11.3
  
  rxdart: ^0.18.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator:
    git: 
      url: https://github.com/efortuna/built_value.dart.git/
      path: built_value_generator

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

